package com.example.hometask_06;

public interface EXTRAS {
    String EXTRA_FOR_CONTACT_NAME = "EXTRA_FOR_CONTACT_NAME" ;
    String EXTRA_FOR_CONTACT_INFO = "EXTRA_FOR_CONTACT_INFO" ;
    String EXTRA_FOR_CONTACT_IS = "EXTRA_FOR_CONTACT_IS" ;
    String EXTRA_FOR_CON_REMOVE = "EXTRA_FOR_CON_REMOVE" ;
}
